apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-web
spec:
  selector:
    matchLabels:
      app: static-web
  replicas: 3    
  template:
    metadata:
      labels:
        app: static-web
    spec:
      containers:
      - name: deploy-web
        image: dandaeki/tomcat:v1.6.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-pull-secret